config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  namespace :admin do
    resources :gists, only: %i[destroy index]
    resources :badges, shallow: true
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passage, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: %i[index]
  resources :user_badges, only: %i[index]

  devise_for :users,
             path_names: {
               sign_in: :login,
               sign_out: :logout
             },
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations'
             }
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < User
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :body, :value, presence: true

  validates :correct, inclusion: [true, false]

  validate :validate_max_answers, on: :create

  scope :correct, -> { where(correct: true) }

  def self.max_answers
    MAX_ANSWERS
  end

  private

  MAX_ANSWERS = 4

  def validate_max_answers
    errors.add(:question) if question.answers.size >= MAX_ANSWERS
    false
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/badge.rb
class Badge < ApplicationRecord
  RULES = [['Пройдены все тесты категории', 'all_tests_of_category_completed'],
           ['Тест пройден с первой попытки', 'success_on_first_try'],
           ['Пройдены все тесты уровня', 'all_tests_of_level_completed']].freeze

  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :test

  validates :title, presence: true

  default_scope { order(title: :asc) }
end

app/models/gist.rb
# frozen_string_literal: true

class Gist < ApplicationRecord
  belongs_to :question, class_name: 'Question', foreign_key: :question_id
  belongs_to :author, class_name: 'User', foreign_key: :author_id, optional: true

  validates :author_id, :question_id, presence: true

  validates :url, :github_gist_id, presence: true, uniqueness: true
end

app/models/passed_test.rb
class PassedTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, class_name: 'Gist', foreign_key: :question_id, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id, optional: true
  belongs_to :category
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :author_id, presence: true

  validates :level, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  validates :ready_to_be_run, inclusion: [true, false]

  validates :title, presence: true,
                    uniqueness: { scope: :level }

  scope :sort_by_category, lambda { |category|
    joins(:category)
      .where(categories: { title: category })
  }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }

  # returns a descending array of names of all Tests whose Category is named in a certain way
  def self.tests_by_category(category)
    sort_by_category(category)
      .order(title: :desc)
      .pluck(:title)
  end
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_first_question, on: %i[create update]

  validates :user_id, :test_id, presence: true

  validates :correct_questions, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  TEST_PASSING_SCORE = 85

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def count_questions
    test.questions.count
  end

  def correct_questions_percentage
    self.correct_questions.to_f / count_questions * 100
  end

  def passed?
    correct_questions_percentage >= TEST_PASSING_SCORE
  end

  private

  def set_first_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if new_record?
      test.questions.first if test.present?
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :confirmable,
         :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages

  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  has_many :authored_tests, class_name: 'Test', foreign_key: :author_id
  has_many :authored_gists, class_name: 'Gist', foreign_key: :author_id

  validates :name, :surname, presence: true

  validates :email, presence: true,
                    uniqueness: true,
                    format: {
                      with: URI::MailTo::EMAIL_REGEXP,
                      message: 'Email template: template@example.com'
                    }

  # returns a list of all Tests that the User passes or has ever passed at this level of difficulty
  def test_by_level(level)
    Test.joins(:test_passages)
        .where('test_passages.user_id = :id AND tests.level = :level', id:, level:)
  end

  # returns the last TestPassage with the Test specified
  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  belongs_to :badge, class_name: 'Badge', foreign_key: :badge_id

  validates :user_id, :badge_id, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_answer_not_found

  private

  def rescue_with_answer_not_found
    render t('.answer_not_found')
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  private

  def rescue_with_question_not_found
    render t('.question_not_found')
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  before_action :find_test, only: %i[start]

  def index
    @tests = Test.where(ready_to_be_run: true)
  end

  def start
    if no_questions?
      flash[:alert] = t('.cannot_start_test')
      redirect_to tests_path
    else
      current_user.tests.push(@test)
      redirect_to current_user.test_passage(@test), status: :see_other, notice: t('.test_started')
    end
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

  def no_questions?
    @test.questions.count.zero? || @test.questions.count.nil?
  end

  def rescue_with_test_not_found
    render t('.test_not_found')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ALERTS = {
    notice: 'info',
    error: 'danger',
    success: 'success',
    alert: 'warning'
  }.freeze

  def current_year
    Date.current.year
  end

  def github_url(author, repo)
    "https://github.com/#{author}/#{repo}"
  end

  def flash_alert(key)
    ALERTS[key.to_sym] if flash[key]
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(test, question)
    if question.persisted?
      t('.header_edit_question', title: question.test.title)
    else
      t('.header_create_new_question', title: test.title)
    end
  end
end

app/helpers/user_badges_helper.rb
module UserBadgesHelper
end

app/views/admin/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg mx-3">
  <div class="container-fluid">
    <a><%= link_to t('.project'), root_path, class: "navbar-brand mb-0 h1" %></a>

    <span class="navbar-brand"><%= t('.admin_panel') %></span>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page"><%= link_to t('.tests'), admin_tests_path %></a>
        <a class="nav-link">
          <%= link_to t('.gists'), admin_gists_path %>
        </a>
        <a class="nav-link">
          <%= link_to t('.badges'), admin_badges_path %>
        </a>
      </div>
    </div>

    <span>
      <%= t('.hello_message', surname: current_user.surname, name: current_user.name) %>
      <%= link_to t('.sign_out'), destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-secondary text-light" %>
    </span>
  </div>
</nav>

app/views/shared/_errors.html.erb
<% if resource.errors.any? %>
  <div style="color: red">
    <h2>
      <%= t('.header', count: resource.errors.count, resource: resource.model_name.human) %>
    </h2>

    <ul>
      <% resource.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-<%= flash_alert(key) %>" role="alert">
    <%= content_tag :p, sanitize(message, attributes: %w[href target]) %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="card text-center stick-to-bottom">
  <div class="card-footer text-body-secondary">
    <nav>
      The <a href=<%= github_url('PrimusInterPares', 'TestGuru') %>>Test Guru project</a> by Alexey Kruglov,
      study project in online-school <%= link_to 'Thinknetica', 'https://thinknetica.com', target: '_blank' %>
    </nav>
    <small>
      <%= current_year %>
    </small>
  </div>
</div>

<style>
    .stick-to-bottom {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        text-align: center;
    }
</style>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-light bg-light mx-3">
  <%= link_to t('.header'), root_path, class: 'navbar-brand' %>

  <span class="navbar-text">
    <% if current_user.is_a?(Admin) %>
      <%= link_to t('.to_admin_panel'),  admin_tests_path, class: "btn btn-primary text-light" %>
    <% end %>
  </span>

  <span class="navbar-text">
    <%= link_to t('user_badges.index.header'),  user_badges_path %>
  </span>

  <span class="navbar-text">
    <% if user_signed_in? %>
      <%= t('.welcome_message', surname: current_user.surname, name: current_user.name) %> |
      <%= link_to t('.sign_out'), destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-secondary text-light" %>
    <% else %>
      <%= link_to t('.sign_in'),  new_user_session_path, class: "btn btn-secondary text-light" %> |
      <%= link_to t('.sign_up'), new_user_registration_path, class: "btn btn-secondary text-light" %>
    <% end %>
  </span>
</nav>