config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  namespace :admin do
    resources :gists, only: %i[destroy index]
    resources :badges, shallow: true
    resources :tests do
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passage, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :badges, only: %i[index]
  resources :user_badges, only: %i[index]

  devise_for :users,
             path_names: {
               sign_in: :login,
               sign_out: :logout
             },
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations'
             }
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  validates :body, :value, presence: true

  validates :correct, inclusion: [true, false]

  validate :validate_max_answers, on: :create

  scope :correct, -> { where(correct: true) }

  def self.max_answers
    MAX_ANSWERS
  end

  private

  MAX_ANSWERS = 4

  def validate_max_answers
    errors.add(:question) if question.answers.size >= MAX_ANSWERS
    false
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_answer_not_found

  before_action :find_answer, only: %i[destroy edit show update]
  before_action :find_question, only: %i[create new]

  def index; end

  def show; end

  def new
    @answer = Answer.new
  end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to [:admin, @answer], status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to [:admin, @answer], status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @answer.destroy
      redirect_to [:admin, @answer.question]
    else
      render html: t('.answer_not_deleted')
    end
  end

  private

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :value, :correct)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def rescue_with_answer_not_found
    render html: t('.answer_not_found')
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_answer_not_found

  private

  def rescue_with_answer_not_found
    render t('.answer_not_found')
  end
end

app/views/answers/_answer.html.erb
<tr>
  <td><%= answer.body %></td>
  <td><%= link_to 'Show', answer_path(answer) %></td>
  <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
  <td>
    <%= link_to 'Delete',
                answer_path(answer),
                data: {
                  turbo_method: :delete,
                  turbo_confirm: 'Are you sure?'
                }
    %>
  </td>
</tr>

app/views/answers/_form.html.erb
<%= form_with model: [@question, @answer] do |form| %>
  <%= render 'shared/errors', resource: @answer %>

  <p>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body, id: :answer_body, value: @answer.body, cols: 30, rows: 3 %>
  </p>

  <p>
    <%= form.label :value, style: "display: block" %>
    <%= form.number_field :value, id: :answer_value, step: '0.1'%>
  </p>

  <p>
    <%= form.label :correct, style: "display: block" %>
    <%= form.check_box :correct, id: :answer_correct %>
  </p>

  <%= form.submit %>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render "form" %>
<br>
<%= link_to "Back to question", question_path(@answer.question) %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<p>
  <%= @question.body %>
</p>

<%= render "form" %>
<br>
<%= link_to "Back to question", question_path(@question) %>

app/views/answers/show.html.erb
<h1>Question</h1>

<p>
  <%= @answer.question.body %>
</p>

<p>
  <b>Answer:</b>
  <%= @answer.body %>
</p>

<p>
  <b>Value:</b>
  <%= @answer.value %>
</p>

<p>
  <b>Correct:</b>
  <%= @answer.correct %>
</p>

<%= link_to "Edit this answer", edit_answer_path(@answer) %>
<%= link_to "Back to question", question_path(@answer.question) %>